name: Test workflow for developing the frizbee-action
on:
  workflow_dispatch:

permissions: write-all

jobs:
  test_pr_and_fail_defaults:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./ # Uses an action in the root directory
        env:
          GITHUB_TOKEN: "fail"
        with:
          open_pr: true
          fail_on_unpinned: true
